apiVersion: v1
kind: Service
metadata:
  name: kopf-operator-service
spec:
  selector:
    app: kopf-operator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort
